In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
performance  = pd.read_csv('performance_train.csv')
facturation  = pd.read_csv('facturation_train.csv')
payments     = pd.read_csv('paiements_train.csv')
transactions = pd.read_csv('transactions_train.csv')

customer_ids = performance['ID_CPTE']

print('Proportion of clients who default:', sum(performance['Default'])/len(performance))

Proportion of clients who default: 0.19336134453781512

In [21]:
default = performance[performance['Default'] == 1]['ID_CPTE']
gen_def = (client for client in default)

### Try not to reset ```default``` too often

In [84]:
next_default_client = next(gen_def)

In [85]:
performance[performance['ID_CPTE'] == next_default_client]

      ID_CPTE PERIODID_MY  Default
378  95510550  2016-12-01        1

In [86]:
facturation[facturation['ID_CPTE'] == next_default_client].sort_values(by='PERIODID_MY')

,ID_CPTE,PERIODID_MY,StatementDate,CurrentTotalBalance,CashBalance,CreditLimit,DelqCycle
5304,95510550,2015-11-01,2015-11-26,1652.54,0.00,7800.0,0
5298,95510550,2015-12-01,2015-12-22,1151.85,353.50,7800.0,0
5296,95510550,2016-01-01,2016-01-21,5319.08,2402.00,7800.0,0
5299,95510550,2016-02-01,2016-02-21,6146.70,0.00,7800.0,0
5303,95510550,2016-03-01,2016-03-20,4906.00,0.00,7800.0,0
5292,95510550,2016-04-01,2016-04-24,0.00,0.00,7800.0,0
5301,95510550,2016-05-01,2016-05-26,1853.94,0.00,7800.0,0
5293,95510550,2016-06-01,2016-06-24,2825.00,0.00,7800.0,0
5295,95510550,2016-07-01,2016-07-21,4122.82,500.00,7800.0,0
5297,95510550,2016-08-01,2016-08-24,7284.16,1314.60,12100.0,0
5294,95510550,2016-09-01,2016-09-24,9838.41,3069.00,12100.0,0
5305,95510550,2016-10-01,2016-10-27,11225.76,3722.16,12100.0,0
5302,95510550,2016-11-01,2016-11-21,11786.32,3545.52,12100.0,0
5300,95510550,2016-12-01,2016-12-21,12165.45,4078.80,12100.0,0

In [87]:
payments[payments['ID_CPTE'] == next_default_client].sort_values(by='TRANSACTION_DTTM')

       ID_CPTE  TRANSACTION_AMT     TRANSACTION_DTTM PAYMENT_REVERSAL_XFLG
6561  95510550            50.00  2016-01-10 00:00:00                     Q
6559  95510550          5456.02  2016-02-04 00:00:00                     Q
6557  95510550          2060.00  2016-02-27 00:00:00                     Q
6558  95510550           121.20  2016-03-22 00:00:00                     Q
6556  95510550          5275.66  2016-04-14 00:00:00                     Q
6569  95510550           588.30  2016-05-08 04:00:00                     Q
6568  95510550            51.50  2016-05-15 00:00:00                     Q
6567  95510550           106.00  2016-06-02 00:00:00                     Q
6565  95510550            63.00  2016-07-21 00:00:00                     Q
6564  95510550            96.30  2016-08-21 00:00:00                     Q
6563  95510550           148.05  2016-09-16 00:00:00                     Q
6562  95510550           206.70  2016-10-15 00:00:00                     Q
6560  95510550           218.16  2016-11-15 00:00:00                     Q
6566  95510550           236.08  2016-12-10 00:00:00                     Q

In [88]:
transactions[transactions['ID_CPTE'] == next_default_client].sort_values(by='TRANSACTION_DTTM')

,ID_CPTE,MERCHANT_CATEGORY_XCD,MERCHANT_CITY_NAME,MERCHANT_COUNTRY_XCD,DECISION_XCD,PRIOR_CREDIT_LIMIT_AMT,TRANSACTION_AMT,TRANSACTION_CATEGORY_XCD,TRANSACTION_DTTM,TRANSACTION_TYPE_XCD,SICGROUP
55988,95510550,EE,2932441,DP,C,4832.0,124.02,E,2016-01-01 12:00:00,F,AX
55954,95510550,YZ,2734290,DP,C,4825.0,46.00,A,2016-01-03 12:00:00,C,AY
56034,95510550,FF,1393143,DP,C,4872.0,40.00,E,2016-01-03 16:00:00,F,BA
56073,95510550,KK,179603,DP,C,4868.0,56.56,D,2016-01-06 16:00:00,F,AT
56120,95510550,QQ,2122999,DP,C,4777.0,1590.00,B,2016-01-08 20:00:00,D,AJ
56114,95510550,AE,1676817,DP,C,3827.0,555.50,E,2016-01-10 16:00:00,F,AU
55984,95510550,BB,1053235,DP,C,4792.0,6.24,B,2016-01-11 00:00:00,F,AA
56086,95510550,PP,2271380,DP,C,4792.0,0.00,A,2016-01-11 00:00:00,G,AA
56085,95510550,PP,2271380,DP,C,4783.0,0.00,A,2016-01-11 00:00:00,G,AA
56011,95510550,JJ,2271380,DP,C,4783.0,6.42,B,2016-01-11 00:00:00,F,AQ
56126,95510550,QQ,2122999,DP,C,4777.0,1010.00,B,2016-01-11 20:00:00,D,AJ
56010,95510550,JJ,2271380,DP,C,4787.0,5.00,B,2016-01-12 00:00:00,F,AQ
56118,95510550,QQ,2122999,DP,C,3277.0,416.00,B,2016-01-15 08:00:00,D,AJ
56077,95510550,KK,179603,DP,C,2877.0,67.00,D,2016-01-16 12:00:00,F,AT
56071,95510550,JJ,735207,DP,C,2810.0,2.06,B,2016-01-22 08:00:00,F,AA
56075,95510550,KK,179603,DP,C,2689.0,84.00,D,2016-01-24 12:00:00,F,AT
56110,95510550,AE,2456002,DP,C,2809.0,94.64,E,2016-01-24 16:00:00,F,AU
56097,95510550,OO,2435198,DP,C,2605.0,30.16,C,2016-01-27 00:00:00,B,AO
56116,95510550,AH,2734290,DP,C,2629.0,22.05,B,2016-01-28 12:00:00,F,AN
56008,95510550,JJ,228090,BB,C,2576.0,9.63,C,2016-01-29 20:00:00,B,AQ
56079,95510550,NN,10760,DP,C,2607.0,109.20,E,2016-02-01 12:00:00,F,BB
55990,95510550,DD,783314,DA,C,2503.0,15.00,B,2016-02-02 20:00:00,F,AA
56017,95510550,HH,2079805,DP,C,7644.0,57.00,E,2016-02-04 16:00:00,F,AE
55970,95510550,F,2122999,DP,C,7586.0,2113.28,B,2016-02-05 08:00:00,F,AR
55971,95510550,F,2122999,DP,C,7586.0,0.00,A,2016-02-05 08:00:00,G,AR
55969,95510550,F,2122999,DP,C,5555.0,3426.14,B,2016-02-05 12:00:00,F,AR
55993,95510550,HH,2079805,DP,C,7660.0,16.64,E,2016-02-05 12:00:00,F,AE
55973,95510550,F,2122999,DP,C,7586.0,0.00,A,2016-02-06 08:00:00,G,AR
55972,95510550,F,2122999,DP,C,5555.0,0.00,A,2016-02-06 12:00:00,G,AR
56024,95510550,HH,8344,DP,C,7759.0,107.00,E,2016-02-07 12:00:00,F,AE
...,...,...,...,...,...,...,...,...,...,...,...
56139,95510550,RR,2122999,DP,C,2311.0,73.00,B,2016-10-21 16:00:00,F,AL
56131,95510550,QQ,2122999,DP,C,2020.0,606.00,B,2016-10-22 12:00:00,D,AJ
56020,95510550,HH,2269449,DP,C,2143.0,127.20,E,2016-10-23 20:00:00,F,AE
56070,95510550,JJ,735207,DP,C,2022.0,2.08,B,2016-10-24 08:00:00,F,AA
56023,95510550,HH,698525,DP,C,1420.0,55.65,E,2016-10-25 20:00:00,F,AE
56003,95510550,JJ,2271380,DP,C,1189.0,9.09,B,2016-10-26 08:00:00,F,AQ
56092,95510550,OO,2435198,DP,C,1218.0,31.03,C,2016-10-27 00:00:00,B,AO
56027,95510550,FF,2709556,DP,C,1181.0,60.00,E,2016-10-27 12:00:00,F,BA
55981,95510550,DD,2114504,DP,C,1367.0,35.02,E,2016-10-27 20:00:00,F,AC
55966,95510550,YZ,777449,DP,C,1085.0,7.00,E,2016-11-01 08:00:00,C,AY
56103,95510550,YZ,2982394,DP,C,1092.0,135.96,E,2016-11-03 20:00:00,F,AG
56032,95510550,FF,777449,DP,C,1135.0,50.50,E,2016-11-05 08:00:00,F,BA
56062,95510550,JJ,735207,DP,C,960.0,43.86,B,2016-11-05 12:00:00,F,AA
56072,95510550,JJ,735207,DP,C,960.0,0.00,A,2016-11-05 12:00:00,G,AA
56033,95510550,FF,777449,DP,C,1134.0,50.50,E,2016-11-16 08:00:00,F,BA
55956,95510550,YZ,777449,DP,C,1084.0,8.24,E,2016-11-16 08:00:00,C,AY
56133,95510550,SS,2533476,AF,C,1092.0,0.00,A,2016-11-17 12:00:00,G,BC
55976,95510550,H,1965711,DP,C,1092.0,220.42,E,2016-11-17 12:00:00,F,BC
55964,95510550,YZ,777449,DP,C,1084.0,53.00,E,2016-11-19 08:00:00,C,AY
56036,95510550,FF,777449,DP,C,1134.0,52.50,E,2016-11-19 08:00:00,F,BA
55977,95510550,H,1965711,DP,C,879.0,26.78,E,2016-11-20 16:00:00,F,BC
56063,95510550,JJ,735207,DP,C,852.0,2.00,B,2016-11-21 08:00:00,F,AA
56095,95510550,OO,2435198,DP,C,767.0,30.16,C,2016-11-26 00:00:00,B,AO
55997,95510550,JJ,2271380,DP,C,738.0,8.08,B,2016-11-30 12:00:00,F,AQ
56130,95510550,QQ,2122999,DP,C,730.0,612.00,B,2016-12-01 08:00:00,D,AJ
55960,95510550,YZ,1965711,DP,C,130.0,28.62,A,2016-12-08 04:00:00,C,AY
55989,95510550,EE,2428887,DP,C,357.0,182.81,E,2016-12-15 16:00:00,F,AX
56056,95510550,JJ,735207,DP,C,177.0,2.06,B,2016-12-21 08:00:00,F,AA
56099,95510550,OO,2435198,DP,C,652.0,29.96,C,2016-12-26 00:00:00,B,AO
56002,95510550,JJ,2271380,DP,C,624.0,8.16,B,2016-12-29 16:00:00,F,AQ