In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
performance  = pd.read_csv('performance_train.csv')
facturation  = pd.read_csv('facturation_train.csv')
payments     = pd.read_csv('paiements_train.csv')
transactions = pd.read_csv('transactions_train.csv')

customer_ids = performance['ID_CPTE']

print('Proportion of clients who default:', sum(performance['Default'])/len(performance))

Proportion of clients who default: 0.19336134453781512

In [3]:
delq_cycle_id = list(set(facturation[facturation['DelqCycle'] > 0]['ID_CPTE']))
condition     = pd.Series([client_id in delq_cycle_id for client_id in performance['ID_CPTE']])

In [4]:
client_list = performance[condition]['ID_CPTE']
gen_def = (client for client in client_list)

### Try not to reset ```default``` too often

In [5]:
next_default_client = next(gen_def)

In [6]:
performance[performance['ID_CPTE'] == next_default_client]

    ID_CPTE PERIODID_MY  Default
1  57427180  2012-12-01        0

In [7]:
facturation[facturation['ID_CPTE'] == next_default_client].sort_values(by='PERIODID_MY')

,ID_CPTE,PERIODID_MY,StatementDate,CurrentTotalBalance,CashBalance,CreditLimit,DelqCycle
26,57427180,2011-11-01,2011-11-04,392.20,0.00,2800.0,0
27,57427180,2011-12-01,2011-12-02,219.00,0.00,2800.0,0
20,57427180,2012-01-01,2012-01-02,233.58,236.08,2800.0,0
25,57427180,2012-02-01,2012-02-03,234.00,0.00,2800.0,0
21,57427180,2012-03-01,2012-03-03,809.12,0.00,2800.0,1
24,57427180,2012-04-01,2012-03-31,1058.84,1.01,2800.0,2
16,57427180,2012-05-01,2012-05-03,260.00,0.00,2800.0,0
19,57427180,2012-06-01,2012-06-02,210.08,0.00,2800.0,0
18,57427180,2012-07-01,2012-07-06,416.00,0.00,2800.0,0
14,57427180,2012-08-01,2012-08-02,243.41,0.00,2800.0,0
23,57427180,2012-09-01,2012-08-31,410.88,0.00,2800.0,0
15,57427180,2012-10-01,2012-10-04,489.72,0.00,2800.0,0
22,57427180,2012-11-01,2012-10-31,689.52,20.00,2800.0,0
17,57427180,2012-12-01,2012-11-29,266.06,0.00,2800.0,0

In [8]:
payments[payments['ID_CPTE'] == next_default_client].sort_values(by='TRANSACTION_DTTM')

     ID_CPTE  TRANSACTION_AMT     TRANSACTION_DTTM PAYMENT_REVERSAL_XFLG
15  57427180           260.00  2012-01-08 00:00:00                     Q
20  57427180           234.60  2012-01-27 00:00:00                     Q
13  57427180          1076.25  2012-04-09 00:00:00                     Q
14  57427180           454.50  2012-05-25 04:00:00                     Q
19  57427180           412.00  2012-06-26 00:00:00                     Q
18  57427180           884.00  2012-07-27 00:00:00                     Q
21  57427180           252.50  2012-08-20 00:00:00                     Q
16  57427180           393.90  2012-09-15 00:00:00                     Q
17  57427180           476.89  2012-10-13 04:00:00                     Q

In [9]:
transactions[transactions['ID_CPTE'] == next_default_client].sort_values(by='TRANSACTION_DTTM')

,ID_CPTE,MERCHANT_CATEGORY_XCD,MERCHANT_CITY_NAME,MERCHANT_COUNTRY_XCD,DECISION_XCD,PRIOR_CREDIT_LIMIT_AMT,TRANSACTION_AMT,TRANSACTION_CATEGORY_XCD,TRANSACTION_DTTM,TRANSACTION_TYPE_XCD,SICGROUP
349,57427180,YZ,1786856,AS,C,2572.0,11.77,C,2012-01-05 20:00:00,B,AB
356,57427180,PP,1923803,AN,C,2808.0,47.84,B,2012-01-09 16:00:00,F,AA
335,57427180,JJ,735207,DP,C,2754.0,15.00,B,2012-01-09 20:00:00,F,AA
332,57427180,KK,2122999,DP,C,2762.0,7.42,E,2012-01-11 16:00:00,F,AT
310,57427180,HH,2122999,DP,C,2739.0,30.30,E,2012-01-14 16:00:00,F,AE
391,57427180,AE,2122999,DP,C,2708.0,318.00,E,2012-01-21 16:00:00,F,AU
343,57427180,KK,2122999,DP,C,2408.0,77.04,E,2012-01-25 16:00:00,F,AT
281,57427180,EE,2122999,DP,C,2537.0,23.46,E,2012-02-03 20:00:00,F,AX
380,57427180,YY,2122999,DP,C,2566.0,18.54,E,2012-02-05 08:00:00,F,AW
348,57427180,YZ,1786856,AS,C,2548.0,11.33,C,2012-02-05 20:00:00,B,AB
390,57427180,AF,422021,DP,C,2514.0,30.00,B,2012-02-08 16:00:00,F,AZ
362,57427180,BC,2122999,DP,C,2415.0,54.06,E,2012-02-15 12:00:00,F,AA
308,57427180,HH,2122999,DP,C,2484.0,72.76,E,2012-02-16 12:00:00,F,AE
355,57427180,PP,1227955,DP,C,2228.0,3.12,B,2012-02-20 16:00:00,F,AA
381,57427180,AC,1630409,DP,C,2364.0,136.00,B,2012-02-21 20:00:00,F,AH
334,57427180,KK,2122999,DP,C,2036.0,9.45,E,2012-02-27 16:00:00,F,AT
252,57427180,T,2122999,DP,C,2225.0,192.78,E,2012-02-28 12:00:00,F,AN
347,57427180,YZ,1786856,AS,C,2021.0,11.44,C,2012-03-03 20:00:00,B,AB
382,57427180,AB,2122999,DP,C,2009.0,9.54,E,2012-03-14 20:00:00,F,AH
323,57427180,KK,2122999,DP,C,1930.0,12.48,E,2012-03-17 12:00:00,F,AT
317,57427180,HH,1701032,DP,C,1999.0,71.40,E,2012-03-17 12:00:00,F,AE
358,57427180,PP,2122999,DP,C,1918.0,43.68,E,2012-03-18 16:00:00,F,AA
273,57427180,EE,2122999,DP,C,1876.0,27.81,E,2012-03-22 16:00:00,F,AX
286,57427180,EE,2122999,DP,C,1848.0,60.18,E,2012-03-25 20:00:00,F,AX
352,57427180,YZ,1786856,AS,C,1789.0,11.22,C,2012-04-05 20:00:00,B,AB
322,57427180,KK,2122999,DP,C,200.0,22.05,E,2012-04-07 12:00:00,F,AT
330,57427180,KK,2122999,DP,C,200.0,21.21,E,2012-04-08 12:00:00,F,AT
331,57427180,KK,2122999,DP,C,2757.0,50.00,E,2012-04-13 20:00:00,F,AT
283,57427180,EE,2122999,DP,C,2786.0,29.00,E,2012-04-17 16:00:00,F,AX
319,57427180,KK,2122999,DP,C,2706.0,19.19,E,2012-04-18 12:00:00,F,AT
...,...,...,...,...,...,...,...,...,...,...,...
280,57427180,EE,2122999,DP,C,2516.0,8.40,E,2012-10-12 20:00:00,F,AX
302,57427180,EE,2122999,DP,C,2508.0,7.21,E,2012-10-13 12:00:00,F,AX
376,57427180,UU,2122999,DP,C,2196.0,114.00,E,2012-10-13 20:00:00,F,AN
318,57427180,KK,2122999,DP,C,2082.0,20.80,E,2012-10-14 12:00:00,F,AT
272,57427180,EE,2122999,DP,C,2524.0,8.56,E,2012-10-15 16:00:00,F,AX
304,57427180,EE,2122999,DP,C,2502.0,9.63,E,2012-10-16 12:00:00,F,AX
266,57427180,EE,2122999,DP,C,2478.0,13.39,E,2012-10-22 12:00:00,F,AX
301,57427180,EE,2122999,DP,C,2494.0,15.15,E,2012-10-22 16:00:00,F,AX
346,57427180,YZ,2122999,DP,C,2453.0,43.00,E,2012-10-24 16:00:00,F,AG
342,57427180,KK,2122999,DP,C,2465.0,12.36,E,2012-10-26 12:00:00,F,AT
366,57427180,QQ,2122999,DP,C,2410.0,20.00,A,2012-10-26 16:00:00,E,AJ
253,57427180,T,2122999,DP,C,2369.0,198.97,E,2012-10-29 16:00:00,F,AN
324,57427180,KK,2122999,DP,C,2380.0,10.10,E,2012-10-30 12:00:00,F,AT
278,57427180,EE,2122999,DP,C,2390.0,11.66,E,2012-11-01 12:00:00,F,AX
306,57427180,HH,2122999,DP,C,2172.0,35.70,E,2012-11-02 16:00:00,F,AE
295,57427180,EE,2122999,DP,C,2081.0,9.00,E,2012-11-03 16:00:00,F,AX
337,57427180,KK,2122999,DP,C,2071.0,40.40,E,2012-11-03 20:00:00,F,AT
314,57427180,HH,2941045,BB,C,2137.0,50.96,B,2012-11-04 20:00:00,F,AE
354,57427180,PP,2271380,DP,C,2137.0,0.00,A,2012-11-05 20:00:00,G,AA
277,57427180,EE,2122999,DP,C,2088.0,7.35,E,2012-11-07 12:00:00,F,AX
269,57427180,EE,2122999,DP,C,2031.0,13.26,E,2012-11-08 20:00:00,F,AX
291,57427180,EE,2122999,DP,C,1960.0,28.62,E,2012-11-10 20:00:00,F,AX
325,57427180,KK,2122999,DP,C,2019.0,30.45,E,2012-11-11 12:00:00,F,AT
328,57427180,KK,2122999,DP,C,1932.0,33.92,E,2012-11-11 16:00:00,F,AT
388,57427180,AF,422021,DP,C,1991.0,10.30,B,2012-11-12 12:00:00,F,AZ
268,57427180,EE,2122999,DP,C,1981.0,12.12,E,2012-11-13 16:00:00,F,AX
270,57427180,EE,2122999,DP,C,1968.0,8.48,E,2012-11-13 20:00:00,F,AX
274,57427180,EE,2122999,DP,B,200.0,11.77,E,2012-11-14 16:00:00,F,AX
293,57427180,EE,2122999,DP,B,200.0,11.44,E,2012-11-15 16:00:00,F,AX
298,57427180,EE,2122999,DP,B,200.0,22.22,E,2012-11-19 16:00:00,F,AX